package config

import (
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	log "github.com/sirupsen/logrus"
	"golang.org/x/crypto/pbkdf2"
)

const (
	DefaultPort     = "3000"
	DefaultDataDir  = "data"
	DefaultTrashDir = "trash"

	// DefaultHost fake url
	DefaultHost = "local.appspot.com"

	EnvLogLevel   = "LOGLEVEL"
	EnvDataDir    = "DATADIR"
	EnvPort       = "PORT"
	EnvStorageURL = "STORAGE_URL"

	// smtp
	envJWTSecretKey     = "JWT_SECRET_KEY"
	envRegistrationOpen = "OPEN_REGISTRATION"
	EnvSmtpServer       = "RM_SMTP_SERVER"
	EnvSmtpUsername     = "RM_SMTP_USERNAME"
	EnvSmtpPassword     = "RM_SMTP_PASSWORD"
	EnvSmtpHelo         = "RM_SMTP_HELO"
	EnvSmtpInsecureTLS  = "RM_SMTP_INSECURE_TLS"
	EnvSmtpFrom         = "RM_SMTP_FROM"

	// myScript hwr api keys
	EnvHwrApplicationKey = "RMAPI_HWR_APPLICATIONKEY"
	EnvHwrHmac           = "RMAPI_HWR_HMAC"
)

// Config config
type Config struct {
	Port             string
	StorageURL       string
	DataDir          string
	JWTSecretKey     []byte
	RegistrationOpen bool
	CreateFirstUser  bool
}

// FromEnv config from environment values
func FromEnv() *Config {
	var err error
	var dataDir string
	data := os.Getenv(EnvDataDir)
	if data != "" {
		dataDir = data
	} else {
		dataDir, err = filepath.Abs(DefaultDataDir)
		if err != nil {
			panic(err)
		}
	}

	port := os.Getenv(EnvPort)
	if port == "" {
		port = DefaultPort
	}

	uploadURL := os.Getenv(EnvStorageURL)
	if uploadURL == "" {
		host, err := os.Hostname()
		if err != nil {
			log.Warn("cannot get hostname")
			host = DefaultHost
		}
		uploadURL = fmt.Sprintf("http://%s:%s", host, port)
	}

	jwtSecretKey := []byte(os.Getenv(envJWTSecretKey))
	if len(jwtSecretKey) == 0 {
		jwtSecretKey = make([]byte, 32)
		_, err := rand.Read(jwtSecretKey)
		if err != nil {
			panic(err)
		}
		log.Warnf("%s was not set! You have to set this variable in order for the Authentication to work, the following was autogenerated", envJWTSecretKey)
		log.Warnf("%s=%X", envJWTSecretKey, jwtSecretKey)
		log.Warn("The authentication will fail, the next time you start the server")
	}
	dk := pbkdf2.Key(jwtSecretKey, []byte("todo some salt"), 10000, 32, sha256.New)

	openRegistration, _ := strconv.ParseBool(os.Getenv(envRegistrationOpen))

	cfg := Config{
		Port:             port,
		StorageURL:       uploadURL,
		DataDir:          dataDir,
		JWTSecretKey:     dk,
		RegistrationOpen: openRegistration,
	}
	return &cfg
}
